version: '2'

## Alternative: use Docker volume. This can get deleted if you're not careful.
#volumes:
#  mongo:

services:
  mongo:
    ## Mongo database for both kadira-engine and kadira-ui
    image: mongo:3.4 # DO NOT UPGRADE MONGO- Kadira needs this version
    volumes:
      - "/Users/miro/Downloads/kadira-mongo:/data/db"
      #- mongo:/data
    command: mongod --smallfiles --replSet kadira
    ports:
      - "27017:27017"
    restart: always

  kadira-engine:
    ## This is the endpoint where Meteor app sends performance data
    image: vladgolubev/kadira-engine
    ports:
      - "11011:11011"
    environment:
      - PORT=11011
      - MONGO_URL=mongodb://mongo/kadira?replicaSet=kadira
      - MONGO_SHARD_URL_one=mongodb://mongo/kadira?replicaSet=kadira
      - VIRTUAL_HOST=${HOST}
      - HTTPS_METHOD=noredirect
    links:
      - mongo
    restart: always

  kadira-rma:
    ## This computes statistics databases every minute.
    image: vladgolubev/kadira-rma
    environment:
      - MONGO_URL=mongodb://mongo/kadira
      - TZ=UTC-1
    links:
      - mongo
    restart: always

  kadira-ui:
    ## Meteor app that presents the Kadira user interface.
    image: vladgolubev/kadira-ui
    ports:
      #- "80:4000"
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongo/kadira
      - MONGO_SHARD_URL_one=mongodb://mongo/kadira
    links:
      - mongo
    restart: always
